POST http://localhost:3000/saveSupervisor
Content-Type: application/json

###

GET http://localhost:3000/getSupervisor

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"tomik",
    "password":"admin"
}

###
POST http://localhost:3000/registration
Content-Type: application/json

{
    "name":"test",
    "password":"test"
}

###
GET http://localhost:3000/logout/?token=test


###

POST http://localhost:3000/userInfo
Content-Type: application/json

{
    "username":"tomik"
}

###

POST http://localhost:3000/saveAttendance
Content-Type: application/json

{
    "username":"tomik"
}

###

POST http://localhost:3000/allUsers
Content-Type: application/json

{
    "id":"5"
}

###

DELETE http://localhost:3000/deleteUser/3

###

POST http://localhost:3000/updateUser
Content-Type: application/json

{
   "id":"2",
   "username":"tominko",
   "role":"USER"
}

###

POST http://localhost:3000/createUser
Content-Type: application/json

{
    "username":"test3",
    "supervisorId":"1",
    "role":"USER",
    "password":"test"
}

###

POST http://localhost:3000/allUsers
Content-Type: application/json

{
    "supervisorId":1
}

###

POST http://localhost:3000/saveAttendance
Content-Type: application/json

{
    "id":"2",
    "worktime":"8",
    "task":"dadada"
}